export interface TUCourse {
  code: string;
  title: string;
  creditHours: number;
  fullMarks: number;
  semesterNumber: number;
  semesterName: string;
  isElective: boolean;
  electiveType?: string;
  program: string;
  oldCode?: string;
}

export const TU_CSIT_PROGRAM_NAME = "B.Sc. CSIT";

export const SEMESTER_LABELS: Record<number, string> = {
  1: "First Semester",
  2: "Second Semester",
  3: "Third Semester",
  4: "Fourth Semester",
  5: "Fifth Semester",
  6: "Sixth Semester",
  7: "Seventh Semester",
  8: "Eighth Semester",
};

/**
 * Tribhuvan University (TU) B.Sc. CSIT Curriculum
 * Updated with the Latest Syllabus Course Codes and Official Paper Titles
 */
export const TU_CSIT_COURSES: TUCourse[] = [
  // ==================== SEMESTER I ====================
  {
    code: "CSC114",
    title: "Introduction to Information Technology",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 1,
    semesterName: "First Semester",
    isElective: false,
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC109",
  },
  {
    code: "CSC115",
    title: "C Programming",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 1,
    semesterName: "First Semester",
    isElective: false,
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC110",
  },
  {
    code: "CSC116",
    title: "Digital Logic",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 1,
    semesterName: "First Semester",
    isElective: false,
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC111",
  },
  {
    code: "MTH117",
    title: "Mathematics I",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 1,
    semesterName: "First Semester",
    isElective: false,
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "MTH112",
  },
  {
    code: "PHY118",
    title: "Physics",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 1,
    semesterName: "First Semester",
    isElective: false,
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "PHY113",
  },

  // ==================== SEMESTER II ====================
  {
    code: "CSC165",
    title: "Discrete Structure",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 2,
    semesterName: "Second Semester",
    isElective: false,
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC160",
  },
  {
    code: "CSC166",
    title: "Object Oriented Programming",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 2,
    semesterName: "Second Semester",
    isElective: false,
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC161",
  },
  {
    code: "CSC167",
    title: "Microprocessor",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 2,
    semesterName: "Second Semester",
    isElective: false,
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC162",
  },
  {
    code: "MTH168",
    title: "Mathematics II",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 2,
    semesterName: "Second Semester",
    isElective: false,
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "MTH163",
  },
  {
    code: "STA169",
    title: "Statistics I",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 2,
    semesterName: "Second Semester",
    isElective: false,
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "STA164",
  },

  // ==================== SEMESTER III ====================
  {
    code: "CSC211",
    title: "Data Structure and Algorithms",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 3,
    semesterName: "Third Semester",
    isElective: false,
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC206",
  },
  {
    code: "CSC212",
    title: "Numerical Method",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 3,
    semesterName: "Third Semester",
    isElective: false,
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC207",
  },
  {
    code: "CSC213",
    title: "Computer Architecture",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 3,
    semesterName: "Third Semester",
    isElective: false,
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC208",
  },
  {
    code: "CSC214",
    title: "Computer Graphics",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 3,
    semesterName: "Third Semester",
    isElective: false,
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC209",
  },
  {
    code: "STA215",
    title: "Statistics II",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 3,
    semesterName: "Third Semester",
    isElective: false,
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "STA210",
  },

  // ==================== SEMESTER IV ====================
  {
    code: "CSC262",
    title: "Theory of Computation",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 4,
    semesterName: "Fourth Semester",
    isElective: false,
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC257",
  },
  {
    code: "CSC263",
    title: "Computer Networks",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 4,
    semesterName: "Fourth Semester",
    isElective: false,
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC258",
  },
  {
    code: "CSC264",
    title: "Operating Systems",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 4,
    semesterName: "Fourth Semester",
    isElective: false,
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC259",
  },
  {
    code: "CSC265",
    title: "Database Management System",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 4,
    semesterName: "Fourth Semester",
    isElective: false,
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC260",
  },
  {
    code: "CSC266",
    title: "Artificial Intelligence",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 4,
    semesterName: "Fourth Semester",
    isElective: false,
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC261",
  },

  // ==================== SEMESTER V ====================
  {
    code: "CSC325",
    title: "Design and Analysis of Algorithms",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 5,
    semesterName: "Fifth Semester",
    isElective: false,
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC314",
  },
  {
    code: "CSC326",
    title: "System Analysis and Design",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 5,
    semesterName: "Fifth Semester",
    isElective: false,
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC315",
  },
  {
    code: "CSC327",
    title: "Cryptography",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 5,
    semesterName: "Fifth Semester",
    isElective: false,
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC316",
  },
  {
    code: "CSC328",
    title: "Simulation and Modeling",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 5,
    semesterName: "Fifth Semester",
    isElective: false,
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC317",
  },
  {
    code: "CSC329",
    title: "Web Technology",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 5,
    semesterName: "Fifth Semester",
    isElective: false,
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC318",
  },
  // Elective I
  {
    code: "CSC330",
    title: "Multimedia Computing",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 5,
    semesterName: "Fifth Semester",
    isElective: true,
    electiveType: "Elective I",
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC319",
  },
  {
    code: "CSC331",
    title: "Wireless Networking",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 5,
    semesterName: "Fifth Semester",
    isElective: true,
    electiveType: "Elective I",
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC320",
  },
  {
    code: "CSC332",
    title: "Image Processing",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 5,
    semesterName: "Fifth Semester",
    isElective: true,
    electiveType: "Elective I",
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC321",
  },
  {
    code: "CSC333",
    title: "Knowledge Management",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 5,
    semesterName: "Fifth Semester",
    isElective: true,
    electiveType: "Elective I",
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC322",
  },
  {
    code: "CSC334",
    title: "Society and Ethics in Information Technology",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 5,
    semesterName: "Fifth Semester",
    isElective: true,
    electiveType: "Elective I",
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC323",
  },
  {
    code: "CSC335",
    title: "Microprocessor Based Design",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 5,
    semesterName: "Fifth Semester",
    isElective: true,
    electiveType: "Elective I",
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC324",
  },

  // ==================== SEMESTER VI ====================
  {
    code: "CSC375",
    title: "Software Engineering",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 6,
    semesterName: "Sixth Semester",
    isElective: false,
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC364",
  },
  {
    code: "CSC376",
    title: "Compiler Design and Construction",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 6,
    semesterName: "Sixth Semester",
    isElective: false,
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC365",
  },
  {
    code: "CSC377",
    title: "E-Governance",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 6,
    semesterName: "Sixth Semester",
    isElective: false,
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC366",
  },
  {
    code: "CSC378",
    title: "NET Centric Computing",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 6,
    semesterName: "Sixth Semester",
    isElective: false,
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC367",
  },
  {
    code: "CSC379",
    title: "Technical Writing",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 6,
    semesterName: "Sixth Semester",
    isElective: false,
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC368",
  },
  // Elective II
  {
    code: "CSC380",
    title: "Applied Logic",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 6,
    semesterName: "Sixth Semester",
    isElective: true,
    electiveType: "Elective II",
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC369",
  },
  {
    code: "CSC381",
    title: "E-commerce",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 6,
    semesterName: "Sixth Semester",
    isElective: true,
    electiveType: "Elective II",
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC370",
  },
  {
    code: "CSC382",
    title: "Automation and Robotics",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 6,
    semesterName: "Sixth Semester",
    isElective: true,
    electiveType: "Elective II",
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC371",
  },
  {
    code: "CSC383",
    title: "Neural Networks",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 6,
    semesterName: "Sixth Semester",
    isElective: true,
    electiveType: "Elective II",
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC372",
  },
  {
    code: "CSC384",
    title: "Computer Hardware Design",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 6,
    semesterName: "Sixth Semester",
    isElective: true,
    electiveType: "Elective II",
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC373",
  },
  {
    code: "CSC385",
    title: "Cognitive Science",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 6,
    semesterName: "Sixth Semester",
    isElective: true,
    electiveType: "Elective II",
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC374",
  },

  // ==================== SEMESTER VII ====================
  {
    code: "CSC419",
    title: "Advanced Java Programming",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 7,
    semesterName: "Seventh Semester",
    isElective: false,
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC409",
  },
  {
    code: "CSC420",
    title: "Data Warehousing and Data Mining",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 7,
    semesterName: "Seventh Semester",
    isElective: false,
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC410",
  },
  {
    code: "MGT421",
    title: "Principles of Management",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 7,
    semesterName: "Seventh Semester",
    isElective: false,
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "MGT411",
  },
  {
    code: "CSC422",
    title: "Project Work",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 7,
    semesterName: "Seventh Semester",
    isElective: false,
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC412",
  },
  // Elective III
  {
    code: "CSC423",
    title: "Information Retrieval",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 7,
    semesterName: "Seventh Semester",
    isElective: true,
    electiveType: "Elective III",
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC413",
  },
  {
    code: "CSC424",
    title: "Database Administration",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 7,
    semesterName: "Seventh Semester",
    isElective: true,
    electiveType: "Elective III",
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC414",
  },
  {
    code: "CSC425",
    title: "Software Project Management",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 7,
    semesterName: "Seventh Semester",
    isElective: true,
    electiveType: "Elective III",
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC415",
  },
  {
    code: "CSC426",
    title: "Network Security",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 7,
    semesterName: "Seventh Semester",
    isElective: true,
    electiveType: "Elective III",
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC416",
  },
  {
    code: "CSC427",
    title: "Digital System Design",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 7,
    semesterName: "Seventh Semester",
    isElective: true,
    electiveType: "Elective III",
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC417",
  },
  {
    code: "MGT428",
    title: "International Marketing",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 7,
    semesterName: "Seventh Semester",
    isElective: true,
    electiveType: "Elective III",
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "MGT418",
  },

  // ==================== SEMESTER VIII ====================
  {
    code: "CSC475",
    title: "Advanced Database",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 8,
    semesterName: "Eighth Semester",
    isElective: false,
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC461",
  },
  {
    code: "CSC476",
    title: "Internship",
    creditHours: 6,
    fullMarks: 200,
    semesterNumber: 8,
    semesterName: "Eighth Semester",
    isElective: false,
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC462",
  },
  // Elective IV & V
  {
    code: "CSC477",
    title: "Advanced Networking with IPV6",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 8,
    semesterName: "Eighth Semester",
    isElective: true,
    electiveType: "Elective IV / V",
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC463",
  },
  {
    code: "CSC478",
    title: "Distributed Networking",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 8,
    semesterName: "Eighth Semester",
    isElective: true,
    electiveType: "Elective IV / V",
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC464",
  },
  {
    code: "CSC479",
    title: "Game Technology",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 8,
    semesterName: "Eighth Semester",
    isElective: true,
    electiveType: "Elective IV / V",
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC465",
  },
  {
    code: "CSC480",
    title: "Distributed and Object-Oriented Database",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 8,
    semesterName: "Eighth Semester",
    isElective: true,
    electiveType: "Elective IV / V",
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC466",
  },
  {
    code: "CSC481",
    title: "Introduction to Cloud Computing",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 8,
    semesterName: "Eighth Semester",
    isElective: true,
    electiveType: "Elective IV / V",
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC467",
  },
  {
    code: "CSC482",
    title: "Geographical Information System",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 8,
    semesterName: "Eighth Semester",
    isElective: true,
    electiveType: "Elective IV / V",
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC468",
  },
  {
    code: "CSC483",
    title: "Decision Support System and Expert System",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 8,
    semesterName: "Eighth Semester",
    isElective: true,
    electiveType: "Elective IV / V",
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC469",
  },
  {
    code: "CSC484",
    title: "Mobile Application Development",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 8,
    semesterName: "Eighth Semester",
    isElective: true,
    electiveType: "Elective IV / V",
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC470",
  },
  {
    code: "CSC485",
    title: "Real Time Systems",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 8,
    semesterName: "Eighth Semester",
    isElective: true,
    electiveType: "Elective IV / V",
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC471",
  },
  {
    code: "CSC486",
    title: "Network and System Administration",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 8,
    semesterName: "Eighth Semester",
    isElective: true,
    electiveType: "Elective IV / V",
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC472",
  },
  {
    code: "CSC487",
    title: "Embedded Systems Programming",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 8,
    semesterName: "Eighth Semester",
    isElective: true,
    electiveType: "Elective IV / V",
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "CSC473",
  },
  {
    code: "MGT488",
    title: "International Business Management",
    creditHours: 3,
    fullMarks: 100,
    semesterNumber: 8,
    semesterName: "Eighth Semester",
    isElective: true,
    electiveType: "Elective IV / V",
    program: TU_CSIT_PROGRAM_NAME,
    oldCode: "MGT474",
  },
];

/**
 * Searches TU courses by query (matches current course code, old course code, or title).
 * Supports search queries like "CSC167", "CSC162", "CSC 167", "microprocessor", "DSA", "211", etc.
 */
export function searchTUCourses(query: string, semesterFilter?: number): TUCourse[] {
  const trimmed = query.trim();
  const normalizedQuery = trimmed.toLowerCase().replace(/\s+/g, "");
  
  return TU_CSIT_COURSES.filter((course) => {
    if (semesterFilter && semesterFilter > 0 && course.semesterNumber !== semesterFilter) {
      return false;
    }
    if (!normalizedQuery) return true;

    const normalizedCode = course.code.toLowerCase().replace(/\s+/g, "");
    const normalizedOldCode = course.oldCode ? course.oldCode.toLowerCase().replace(/\s+/g, "") : "";
    const normalizedTitle = course.title.toLowerCase().replace(/\s+/g, "");
    const rawTitleLower = course.title.toLowerCase();

    return (
      normalizedCode.includes(normalizedQuery) ||
      (normalizedOldCode && normalizedOldCode.includes(normalizedQuery)) ||
      normalizedTitle.includes(normalizedQuery) ||
      rawTitleLower.includes(trimmed.toLowerCase())
    );
  });
}
